### ISSUE TITLE
Add RBAC support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#162]
As a developer, I'd like to study the applicability of RBAC support in the deployer implementation, so we can prepare for k8s 1.8.x compatibility.

Notes: 
- [1.8.x release](http://blog.kubernetes.io/2017/09/kubernetes-18-security-workloads-and.html) supports RBAC and if it is enabled, the deployer implementation requires a `ServiceAccount ` and a `Role` to gain access to K8S APIs
- We would still have to identify the fabric8 client that's compatible with 1.8.x (2.5.9 appears to be a good candidate)
- The goal of this spike is to study the applicability of RBAC and the deployer specific support for it

**Comment by viniciusccarvalho** [comment]
Here's what I found so far testing on GKE 1.8.x

It appears that now GKE enables RBAC by default, which causes our tests to fail, however, deploying the server using the instructions, it work as expected.

It seems that the scope given to an application running inside a POD are different than a process running locally using the fabric8 DefaultKubernetesClient.

According to the docs, every app deployed on the cluster gets assigned a default service account that would give the same permissive permissions as before RBAC, in order to keep backward compatibility.

So this seems to be the reason why inside the cluster the server is working. So as far as the server deployment is concerned there's nothing we need to do on our end, but we need to fix testing, so I'll look further.

@trisberg and @markpollack what's your take on this? Do we need to investigate further on deployment aspect given that its working? Or should we just keep an eye on how to make tests work again?

**Comment by trisberg** [comment]
I think any app that accesses the k8s API server needs to have the proper RBAC permissions. This would in our case be the SCDF server/deployer app.

**Comment by mv78** [comment]
We are currently in the process of deploying our stream applications that depend on specific service account that allows to assume AWS role to grant temporary credentials via Kube2iam. In order to make this work, we need to add RBAC sericeAccount to Deployment Pod Spec and also have ability to pass annotations (i.e. iam.amazonaws.com/role) to Deployment Pod's Spec Template.

As far as I can tell, we need to modify KubernetesAppDeployer to have ability to pass 


DeploymentBuilder().
	withNewMetadata().withName(appId).withLabels(idMap)
			.addToLabels(SPRING_MARKER_KEY, SPRING_MARKER_VALUE).endMetadata()
	.withNewSpec().withReplicas(replicas)
		.withNewTemplate().
			withNewMetadata().withLabels(idMap).addToLabels(SPRING_MARKER_KEY, SPRING_MARKER_VALUE) . <--- add custom annotations  
				.endMetadata(). 
			withSpec(createPodSpec(appId, request, Integer.valueOf(externalPort), false)).endTemplate()
			.endSpec().build(); 

Modify AbstractKubernetesDeployer to pass custom RBAC service account to createPodSpec method and add it to the Pod's Spec "withServiceAccount".

**Comment by dturanski** [comment]
@trisberg - Do you see any existing additional scope for this or are you just suggesting that this is a cross cutting concern going forward?

**Comment by mv78** [comment]
Yes its cross cutting concern going forward. It would be nice to also pass annotations to service level and have environment variables of deployed boot app to read value from secret (i.e AWS key/secret for testing etc)

Example:
            "name": "AWS_ACCESS_KEY_ID",
            "valueFrom": {
              "secretKeyRef": {
                "name": "homeaway-uk-warranty-document-service",
                "key": "AWS_ACCESS_KEY_ID"
              }
            }
          },
          {
            "name": "AWS_SECRET_ACCESS_KEY",
            "valueFrom": {
              "secretKeyRef": {
                "name": "homeaway-uk-warranty-document-service",
                "key": "AWS_SECRET_ACCESS_KEY"
              }
            }
          }

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#243
