### ISSUE TITLE
Update Spring Cloud Deployer to 2.0.x (Local Deployer already updated)

### ISSUE THREAD

**Issue by Salaboy** [spring-cloud/spring-cloud-deployer-kubernetes#176]
I was planning to do this update now and send a PR for the new 2.0.x branch. I'm interested in knowing if we might move this module closer to: https://github.com/spring-cloud-incubator/spring-cloud-kubernetes which is extremely similar dependency wise and also needs to be updated to work with 2.0.x. 

I'm more than happy to start that work if someone can review and merge when it is done. 

Cheers

**Comment by sabbyanandan** [comment]
Hi, @Salaboy. I can't speak to the incubator project since I believe it is largely community maintained; however, from the [Deployer SPI](https://github.com/spring-cloud/spring-cloud-deployer) and the implementations POV, we maintain these projects. It has standalone use, of course (you're interested in it!), but the primary driver is Spring Cloud Data Flow. 

The current 1.x line (1.3 is at RC1) is the production version of the K8S-deployer and we do not have immediate plans to switch to 2.0. The library doesn't use Boot; there's a Resource dependency from Spring Framework, and that's about it. In case you're wondering, we thought about moving to 2.0 (hence, the 2.0.x branch in Local-deployer), but we have decided to continue on the 1.x line for now.

May I ask why you're interested in the 2.x line? What is that you're expecting from the upgrade?

**Comment by Salaboy** [comment]
@sabbyanandan thanks for getting back about this and for the amount of detail in the answer. 
We are looking forward to use the SPI Deployer APIs to deploy both local (for dev purposes) and in k8s in a similar fashion as in Spring Data Flow but for different purposes. We are building a high level service to do an aggregation of several spring boot apps into one single Logical App concept, we want to use the deployers to provision these apps and each of the internal pieces. 
What we will expect from the update is to have the same SPI for both local and k8s and similar dependencies from the spring boot and spring side. 
Does this make sense?

**Comment by sabbyanandan** [comment]
Thanks for the background. Unfortunately, it is still unclear why being on 2.0 release-line is useful. Since we don't rely on Boot/Cloud 2.0 at the deployer level, we don't expect any benefits from the upgrade.

**Comment by Salaboy** [comment]
@sabbyanandan ok sounds good, I will give it a try as it is. 
But the main problem that I see is that if you want to move Data Flow to Boot/Cloud 2.0 you will depend on an old spring version for the kube deployer. 

My main use case right now is a Spring Boot / Cloud 2.0 service that wants to use the local and kube deployer, for such use case I will end up with a mess of dependencies and hence I decided to see if I can upgrade the k8s to 2.0. I do recognise that there is not benefit from the K8S point of view, but at the dependency level it sounds the right thing to do. 

In the case that I can successfully update the module, are you OK with accepting a PR to create the branch 2.0.x as in the local deployer?

**Comment by sabbyanandan** [comment]
@markpollack: See gitter-conversation [here](https://gitter.im/spring-cloud/spring-cloud-stream?at=5a71e5a0b3c4a0d376c2c9bc). What are your thoughts? We could consider a 2.x branch and have @Salaboy contribute the upgrade PR to unblock his progress.

**Comment by markpollack** [comment]
Here is a 2.0.x branch for you @Salaboy - thanks!

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/tree/2.0.x
