### ISSUE TITLE
Support deployment options in Scheduler CronJob's

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-deployer-kubernetes#331]
CronJob's in the merged Scheduler API should be able to take advantage of deployment options like volume mounts and so on. This was left out during the consolidation. Leaving this open ended for now until scope is understood.

**Comment by eskuai** [comment]
Hi @sabbyanandan 

Can I request a rethinking and replaning of task #331 to include it into interation 157 -> 2.3.0.GA ??

We think that it is a very important option on k8s scdf ...  we are planning a intensive use of scheduling task ...

**Comment by chrisjs** [comment]
this type of change is not suited to be done in a GA release. its expected to begin start of 2.4

**Comment by sabbyanandan** [comment]
@eskuai: To expand to what @chrisjs had pointed out, we ended up discovering the feature gap way beyond the 2.3 RC timeline, and we typically avoid a large set of refactoring changes and/or feature additions once when the RC milestone is reached.

All that said, this has been prioritized for the next minor, 2.4 release. Feel free to track the story for incremental progress, so you could consume one of the early 2.4 milestones to validate it for us.

**Comment by eskuai** [comment]
Hi @chrisjs  @sabbyanandan 

Ok, we'll validate with 2.4 milestone .. 

We're trying to apply streaming with trigger|task-deploy in the meantime

Thank you

**Comment by ilayaperumalg** [comment]
After some internal discussion on this, we have decided not to add this feature based on the recent scheduler changes in Spring Cloud Data Flow (from task CI/CD feature). Here is the summary of the discussion:

 - The SCDF 2.3.x and above use the `scheduler-task-launcher` app to schedule the task applications. The `scheduler-task-launcher` acts as a REST client app to launch the underlying task application by issuing REST request to SCDF server. When a cron job is created upon creating a new schedule for a task, the cronjob's functionality is to schedule the launch of the `scheduler-task-launcher` app only. The cronjob doesn't *directly* invoke the actual task application. 

Because of this, the `scheduler` properties that are passed when creating a schedule are essentially applied to the `scheduler-task-launcher` app only. Also, the cronjob configuration is also applied to the `scheduler-task-launcher` app only. This also means, if someone edits the cronjob configuration outside of SCDF, it doesn't get propagated to the task application. 

Since the idea of passing the scheduler properties at the time of schedule creation would just be applied to the `scheduler-task-launcher` job, it is decided not to support this for now. If someone wants to pass the deployer properties to the underlying task app, they can be passed via the regular `deployer.<task-app-name>.kubernetes.*`.

**Comment by ilayaperumalg** [comment]
The actual scope of this issue was to merge the scheduler properties as deployer properties and the corresponding changes were made [here](https://github.com/ilayaperumalg/spring-cloud-deployer-kubernetes/commit/11e081f6db8e6a8caa17786a59ea6450d6a9190a). In case if we want to revisit in future, we can take some of these code changes.

**Comment by ilayaperumalg** [comment]
Marking this as spike and closing it for now. 

Created a follow-up issue on SCDF to pass the scheduler properties to the task job: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3714
