### ISSUE TITLE
Deploying an sidecar container

### ISSUE THREAD

**Issue by canerkoseren** [spring-cloud/spring-cloud-deployer-kubernetes#414]
**Problem description:**
We want to deploy a sidecar container inside the pod where batch-applications running in OpenShift.

**Solution description:**
We want to use a different tool to keep secrets. For this solution we are supposed to deploy a sidecar container.

We are using the 2.7.0-RC1 version of scdf. In this version, we can deploy only one container inside a pod. It is possible to deploy more than one container in a pod?

**Description of alternatives:**
Is it possible to customize default deployment config?

**Comment by umutcann** [comment]
Hi @ilayaperumalg 

I begin to implement a contribution that users are able to set kubernetes deploymentYaml during SCDF task launch. It seems that It's working properly. 

Before open pull-request, I would like to ask a question. 

We are using Openshift for cloud environment. So that, we are using deploymentConfig instead of Deployment. We want to adapt this feature for Openshift. If we adapt this feature for Openshift in your project, what will be your approach on this idea?

**Comment by ilayaperumalg** [comment]
Hi @umutcann , Thanks for your interest in getting this.

Having Openshift specific changes in this project wouldn't be a better idea and hence you could submit a PR that conforms to the `spring-cloud-deployer-kubernetes` contracts. You can still have all the deployer properties specific to `sidecar` container in here and setting those properties for `Deployment` instead when you submit a PR on this project.

**Comment by umutcann** [comment]
Hi @ilayaperumalg 

As you know all of container configurations are managed by deploymentYaml.

In order to pass arguments like SPRING_DATASOURCE_URL, SPRING_CLOUD_TASK_EXECUTIONID vs to launching app using kubernetes deployment yaml, I need to use that code blocks in KubernetesTaskLauncher class. 

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/1dcbc489e578165efa5ad2336b115e9487ee82fd/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DefaultContainerFactory.java#L100

I think that I should create a util class to prevent code duplications. Should I use create this util class in support module?

And may you please point me contribution document of this repository?

**Comment by ilayaperumalg** [comment]
Sure, if it makes sense to create a util class please do so. But, please avoid having any references on OpenStack in this project as `spring-cloud-deployer-kubernetes` isn't designed to have any tight coupling to platform. 

We don't have explicit documentation to walk you through the code specifics on this project. Nevertheless this project project is a smaller deployer implementation and easy to follow from the existing codebase. If you have any specific questions, please feel free to ask and we'd be happy to help. Thanks again for looking into this.

**Comment by umutcann** [comment]
Hi @ilayaperumalg 

I opened a [pull-request](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/422) in order to support deploy apps using kubernetes native deployment yaml.

I'm expecting your worthy comments.

Thanks.

**Comment by umutcann** [comment]
Hi @ilayaperumalg ,

Is there any planned date for related PR merge?

Thanks.

**Comment by isha1kh** [comment]
Hi @ilayaperumalg - I need a sidecar for my use case too, can you please consider releasing this asap?

**Comment by ilayaperumalg** [comment]
Hi @umutcann @isha1kh, We are planning to get this PR merged in the upcoming release. The date isn't finalised for this release yet.

**Comment by isha1kh** [comment]
Hi @ilayaperumalg, I know its not finalised yet but may I know the tentative release date for this change please?

**Comment by ilayaperumalg** [comment]
Hi @isha1kh Tentative date would be mid-May. Thanks!

**Comment by isha1kh** [comment]
Thanks @ilayaperumalg, wondering if there's any milestone release with this change that I can try out earlier? 

Or is there any other way to get the server image with the sidecar changes faster, do I need to build a custom one myself?

**Comment by ilayaperumalg** [comment]
Yes, there will be a milestone by the end of this month or you can try out the SCDF server/Skipper server snapshot images as soon as this PR is merged.

**Comment by isha1kh** [comment]
Thanks @ilayaperumalg, I've approved it but you probably need your colleague's approval. Would be nice to get the snapshot image ASAP.

**Comment by ilayaperumalg** [comment]
Thank you for verifying and approving. yeah, I will need one other approval.
