### ISSUE TITLE
The worker pod launched by SCDF is preempted and killed by kubernetes system-pods - adding property for priorityClassName

### ISSUE THREAD

**Issue by thesoundofsilent** [spring-cloud/spring-cloud-deployer-kubernetes#466]
When using deployer partitions to launch 50+ or more pod, it is high probability that one or more pods are killed by kubernetes system pods like kube-system/calico-node-8xc5f

Is there anything we can do for this issue? is it possible to suppport priority class properties in SCDF to let me set the priority for the worker pod thus it will not be preeempted? or is there any suggestion?

**Comment by sabbyanandan** [comment]
@thesoundofsilent: Can you expand and clarify what do you mean by "one or more pods are killed by kubernetes system pods like kube-system/calico-node-8xc5f", please? 

Any specific details as to the reason or why the case would help. Besides what we support at the level of deployer APIs (that interact with the API Server behind the scenes), it is unclear how we can help with the prevention of such a thing that is happening due to other components running in a given K8s cluster.

**Comment by markpollack** [comment]
Looks like we should add a 'mirrored' deployer property for `priorityClassName`.
