### ISSUE TITLE
Configure tests to not use 8080 port in KubernetesTestSupport rule

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#51]
See: https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/d4a644db19d53e5a5cb3e2a4ba0d12dfde1c7bc0

**Comment by ericbottard** [comment]
Yes, the problem (or maybe _one of the problems_) is not with tests themselves, but with the JUnit rule that creates an ApplicationContext and that (because of AutoConfiguration) created a default tomcat instance listening on 8080.

ITs that don't need a webserver (most don't) can and should also disable theirs as well
